# Generated by Django 5.2.6 on 2025-09-27 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SeatingArrangement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.IntegerField()),
                ('bench_number', models.IntegerField()),
                ('student1', models.CharField(blank=True, max_length=20, null=True)),
                ('student2', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
